import { Meal } from './types';

export const BREAKFASTS: Meal[] = [
  {
    name: 'Greek Yogurt Parfait',
    calories: 320,
    protein: 20,
    carbs: 38,
    fat: 8,
    ingredients: ['greek yogurt', 'mixed berries', 'granola', 'honey'],
    tags: ['high_protein', 'vegetarian'],
    goals: ['lose_weight', 'eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Scrambled Eggs & Avocado Toast',
    calories: 410,
    protein: 22,
    carbs: 30,
    fat: 22,
    ingredients: ['eggs', 'whole grain bread', 'avocado', 'cherry tomatoes'],
    tags: ['high_protein', 'vegetarian', 'low_carb'],
    goals: ['gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Overnight Oats',
    calories: 360,
    protein: 12,
    carbs: 55,
    fat: 8,
    ingredients: ['rolled oats', 'almond milk', 'chia seeds', 'banana', 'peanut butter'],
    tags: ['vegetarian'],
    goals: ['eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Protein Smoothie Bowl',
    calories: 380,
    protein: 30,
    carbs: 42,
    fat: 7,
    ingredients: ['protein powder', 'frozen berries', 'spinach', 'almond milk', 'granola', 'flaxseeds'],
    tags: ['high_protein', 'vegetarian'],
    goals: ['gain_muscle', 'lose_weight'],
  },
  {
    name: 'Veggie Omelette',
    calories: 290,
    protein: 24,
    carbs: 8,
    fat: 18,
    ingredients: ['eggs', 'bell peppers', 'spinach', 'mushrooms', 'feta cheese'],
    tags: ['high_protein', 'vegetarian', 'low_carb'],
    goals: ['lose_weight', 'eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Chia Seed Pudding',
    calories: 280,
    protein: 9,
    carbs: 32,
    fat: 14,
    ingredients: ['chia seeds', 'coconut milk', 'mango', 'vanilla extract'],
    tags: ['vegetarian', 'low_carb'],
    goals: ['lose_weight', 'eat_healthy'],
  },
  {
    name: 'Cottage Cheese & Berries',
    calories: 260,
    protein: 25,
    carbs: 22,
    fat: 5,
    ingredients: ['cottage cheese', 'strawberries', 'blueberries', 'almonds'],
    tags: ['high_protein', 'vegetarian', 'low_carb'],
    goals: ['lose_weight', 'gain_muscle'],
  },
  {
    name: 'Turkey & Egg White Wrap',
    calories: 350,
    protein: 35,
    carbs: 28,
    fat: 9,
    ingredients: ['egg whites', 'turkey breast', 'whole wheat wrap', 'spinach', 'salsa'],
    tags: ['high_protein'],
    goals: ['lose_weight', 'gain_muscle'],
  },
  {
    name: 'Almond Butter Banana Toast',
    calories: 340,
    protein: 10,
    carbs: 44,
    fat: 15,
    ingredients: ['whole grain bread', 'almond butter', 'banana', 'cinnamon'],
    tags: ['vegetarian'],
    goals: ['eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Smoked Salmon Bagel',
    calories: 420,
    protein: 28,
    carbs: 40,
    fat: 14,
    ingredients: ['whole wheat bagel', 'smoked salmon', 'cream cheese', 'capers', 'red onion', 'cucumber'],
    tags: ['high_protein'],
    goals: ['eat_healthy', 'gain_muscle'],
  },
];

export const LUNCHES: Meal[] = [
  {
    name: 'Grilled Chicken Salad',
    calories: 380,
    protein: 38,
    carbs: 18,
    fat: 16,
    ingredients: ['chicken breast', 'mixed greens', 'cherry tomatoes', 'cucumber', 'olive oil', 'lemon'],
    tags: ['high_protein', 'low_carb'],
    goals: ['lose_weight', 'gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Quinoa & Black Bean Bowl',
    calories: 430,
    protein: 18,
    carbs: 60,
    fat: 12,
    ingredients: ['quinoa', 'black beans', 'corn', 'avocado', 'lime', 'cilantro'],
    tags: ['vegetarian'],
    goals: ['eat_healthy', 'lose_weight'],
  },
  {
    name: 'Turkey & Veggie Wrap',
    calories: 390,
    protein: 30,
    carbs: 36,
    fat: 11,
    ingredients: ['turkey breast', 'whole wheat wrap', 'lettuce', 'tomato', 'hummus', 'bell pepper'],
    tags: ['high_protein'],
    goals: ['lose_weight', 'eat_healthy'],
  },
  {
    name: 'Tuna Nicoise Salad',
    calories: 360,
    protein: 32,
    carbs: 20,
    fat: 14,
    ingredients: ['canned tuna', 'hard boiled eggs', 'green beans', 'olives', 'cherry tomatoes', 'olive oil'],
    tags: ['high_protein', 'low_carb'],
    goals: ['lose_weight', 'eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Lentil Soup',
    calories: 340,
    protein: 20,
    carbs: 50,
    fat: 5,
    ingredients: ['lentils', 'carrots', 'celery', 'onion', 'garlic', 'cumin', 'turmeric'],
    tags: ['vegetarian'],
    goals: ['eat_healthy', 'lose_weight'],
  },
  {
    name: 'Salmon & Brown Rice Bowl',
    calories: 520,
    protein: 40,
    carbs: 45,
    fat: 16,
    ingredients: ['salmon fillet', 'brown rice', 'edamame', 'cucumber', 'soy sauce', 'sesame seeds'],
    tags: ['high_protein'],
    goals: ['gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Caprese Salad with Chickpeas',
    calories: 360,
    protein: 16,
    carbs: 30,
    fat: 18,
    ingredients: ['fresh mozzarella', 'tomatoes', 'chickpeas', 'basil', 'balsamic vinegar', 'olive oil'],
    tags: ['vegetarian'],
    goals: ['eat_healthy'],
  },
  {
    name: 'Chicken & Avocado Caesar Wrap',
    calories: 470,
    protein: 40,
    carbs: 32,
    fat: 20,
    ingredients: ['grilled chicken', 'romaine lettuce', 'parmesan', 'whole wheat wrap', 'avocado', 'caesar dressing'],
    tags: ['high_protein'],
    goals: ['gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Zucchini Noodle Pad Thai',
    calories: 310,
    protein: 20,
    carbs: 18,
    fat: 16,
    ingredients: ['zucchini', 'shrimp', 'egg', 'peanuts', 'lime', 'fish sauce', 'green onion'],
    tags: ['low_carb'],
    goals: ['lose_weight', 'eat_healthy'],
  },
  {
    name: 'Greek Chicken Pita',
    calories: 450,
    protein: 36,
    carbs: 40,
    fat: 12,
    ingredients: ['chicken breast', 'pita bread', 'tzatziki', 'tomato', 'red onion', 'cucumber', 'feta'],
    tags: ['high_protein'],
    goals: ['gain_muscle', 'eat_healthy'],
  },
];

export const DINNERS: Meal[] = [
  {
    name: 'Baked Salmon with Asparagus',
    calories: 480,
    protein: 42,
    carbs: 12,
    fat: 28,
    ingredients: ['salmon fillet', 'asparagus', 'lemon', 'garlic', 'olive oil', 'dill'],
    tags: ['high_protein', 'low_carb'],
    goals: ['lose_weight', 'gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Chicken Stir Fry with Vegetables',
    calories: 440,
    protein: 40,
    carbs: 35,
    fat: 14,
    ingredients: ['chicken breast', 'broccoli', 'bell peppers', 'snap peas', 'ginger', 'soy sauce', 'sesame oil'],
    tags: ['high_protein'],
    goals: ['lose_weight', 'gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Vegetable Curry with Chickpeas',
    calories: 420,
    protein: 18,
    carbs: 52,
    fat: 14,
    ingredients: ['chickpeas', 'tomatoes', 'spinach', 'coconut milk', 'curry powder', 'ginger', 'garlic', 'brown rice'],
    tags: ['vegetarian'],
    goals: ['eat_healthy'],
  },
  {
    name: 'Turkey Meatballs with Zucchini Noodles',
    calories: 400,
    protein: 38,
    carbs: 16,
    fat: 18,
    ingredients: ['ground turkey', 'zucchini', 'tomato sauce', 'parmesan', 'garlic', 'basil', 'onion'],
    tags: ['high_protein', 'low_carb'],
    goals: ['lose_weight', 'gain_muscle'],
  },
  {
    name: 'Stuffed Bell Peppers',
    calories: 390,
    protein: 30,
    carbs: 36,
    fat: 12,
    ingredients: ['bell peppers', 'ground beef', 'brown rice', 'tomato sauce', 'onion', 'garlic', 'cheese'],
    tags: ['high_protein'],
    goals: ['gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Shrimp Tacos with Slaw',
    calories: 410,
    protein: 30,
    carbs: 40,
    fat: 14,
    ingredients: ['shrimp', 'corn tortillas', 'cabbage', 'lime', 'cilantro', 'avocado', 'jalapeño'],
    tags: ['high_protein'],
    goals: ['eat_healthy', 'lose_weight'],
  },
  {
    name: 'Cauliflower Fried Rice',
    calories: 320,
    protein: 16,
    carbs: 20,
    fat: 18,
    ingredients: ['cauliflower', 'eggs', 'peas', 'carrots', 'soy sauce', 'sesame oil', 'green onion'],
    tags: ['vegetarian', 'low_carb'],
    goals: ['lose_weight', 'eat_healthy'],
  },
  {
    name: 'Grilled Cod with Sweet Potato',
    calories: 450,
    protein: 36,
    carbs: 44,
    fat: 10,
    ingredients: ['cod fillet', 'sweet potato', 'broccoli', 'lemon', 'paprika', 'olive oil'],
    tags: ['high_protein'],
    goals: ['eat_healthy', 'lose_weight'],
  },
  {
    name: 'Black Bean Tacos',
    calories: 370,
    protein: 16,
    carbs: 52,
    fat: 10,
    ingredients: ['black beans', 'corn tortillas', 'avocado', 'salsa', 'red cabbage', 'lime', 'cilantro'],
    tags: ['vegetarian'],
    goals: ['eat_healthy'],
  },
  {
    name: 'Beef & Broccoli',
    calories: 490,
    protein: 44,
    carbs: 22,
    fat: 24,
    ingredients: ['lean beef', 'broccoli', 'garlic', 'ginger', 'soy sauce', 'sesame oil', 'brown rice'],
    tags: ['high_protein', 'low_carb'],
    goals: ['gain_muscle'],
  },
];

export const SNACKS: Meal[] = [
  {
    name: 'Apple with Almond Butter',
    calories: 200,
    protein: 5,
    carbs: 28,
    fat: 10,
    ingredients: ['apple', 'almond butter'],
    tags: ['vegetarian'],
    goals: ['lose_weight', 'eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Protein Bar',
    calories: 220,
    protein: 20,
    carbs: 24,
    fat: 7,
    ingredients: ['protein bar'],
    tags: ['high_protein'],
    goals: ['gain_muscle', 'lose_weight'],
  },
  {
    name: 'Mixed Nuts & Dried Fruit',
    calories: 180,
    protein: 5,
    carbs: 20,
    fat: 12,
    ingredients: ['almonds', 'walnuts', 'dried cranberries', 'cashews'],
    tags: ['vegetarian', 'low_carb'],
    goals: ['eat_healthy', 'lose_weight'],
  },
  {
    name: 'Hummus & Veggies',
    calories: 160,
    protein: 6,
    carbs: 20,
    fat: 8,
    ingredients: ['hummus', 'carrots', 'celery', 'bell pepper strips'],
    tags: ['vegetarian', 'low_carb'],
    goals: ['lose_weight', 'eat_healthy'],
  },
  {
    name: 'Hard Boiled Eggs',
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    ingredients: ['eggs'],
    tags: ['high_protein', 'low_carb'],
    goals: ['lose_weight', 'gain_muscle'],
  },
  {
    name: 'Greek Yogurt with Walnuts',
    calories: 190,
    protein: 14,
    carbs: 12,
    fat: 10,
    ingredients: ['greek yogurt', 'walnuts', 'honey'],
    tags: ['high_protein', 'vegetarian'],
    goals: ['gain_muscle', 'eat_healthy'],
  },
  {
    name: 'Edamame',
    calories: 150,
    protein: 12,
    carbs: 14,
    fat: 5,
    ingredients: ['edamame', 'sea salt'],
    tags: ['vegetarian', 'high_protein'],
    goals: ['lose_weight', 'eat_healthy', 'gain_muscle'],
  },
  {
    name: 'Cottage Cheese & Pineapple',
    calories: 170,
    protein: 15,
    carbs: 18,
    fat: 3,
    ingredients: ['cottage cheese', 'pineapple chunks'],
    tags: ['high_protein', 'vegetarian'],
    goals: ['lose_weight', 'gain_muscle'],
  },
];
